import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { sendEmail, buildOrderConfirmationEmail } from "@/lib/email";

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Vui lòng đăng nhập" }, { status: 401 });
    }

    const body = await request.json();
    const {
      items,
      subtotal,
      delivery_fee,
      total,
      payment_method,
      delivery_address,
      branch_id,
      note,
      points_used,
      points_discount,
      voucher_id,
      voucher_code,
      voucher_discount,
      combo_savings,
      gifts,
    } = body;

    if (!items || items.length === 0) {
      return NextResponse.json({ error: "Giỏ hàng trống" }, { status: 400 });
    }

    // Create order
    const { data: order, error: orderError } = await supabase
      .from("orders")
      .insert({
        user_id: user.id,
        subtotal,
        delivery_fee: delivery_fee || 0,
        discount: (voucher_discount || 0) + (combo_savings || 0) + (points_discount || 0),
        total,
        payment_method,
        payment_status: payment_method === "cod" ? "unpaid" : "unpaid",
        status: "pending",
        delivery_address,
        branch_id: branch_id || null,
        note,
        order_number: "", // Will be auto-generated by trigger
        voucher_id: voucher_id || null,
        voucher_code: voucher_code || null,
        voucher_discount: voucher_discount || 0,
        points_used: points_used || 0,
        points_discount: points_discount || 0,
        combo_savings: combo_savings || 0,
        gifts: gifts || [],
      })
      .select()
      .single();

    if (orderError) {
      console.error("Order creation error:", orderError);
      return NextResponse.json(
        { error: "Không thể tạo đơn hàng" },
        { status: 500 }
      );
    }

    // Create order items
    const orderItems = items.map((item: any) => ({
      order_id: order.id,
      product_id: item.product_id,
      product_name: item.product_name,
      product_price: item.product_price,
      quantity: item.quantity,
      subtotal: item.subtotal,
    }));

    const { error: itemsError } = await supabase
      .from("order_items")
      .insert(orderItems);

    if (itemsError) {
      console.error("Order items error:", itemsError);
    }

    // Handle payment methods
    if (payment_method === "vnpay") {
      const payRes = await fetch(
        `${process.env.NEXT_PUBLIC_APP_URL}/api/payment/vnpay/create`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            order_id: order.id,
            amount: total,
            order_number: order.order_number,
          }),
        }
      );
      const payData = await payRes.json();
      if (payData.paymentUrl) {
        return NextResponse.json({
          order_number: order.order_number,
          paymentUrl: payData.paymentUrl,
        });
      }
    }

    if (payment_method === "momo") {
      const payRes = await fetch(
        `${process.env.NEXT_PUBLIC_APP_URL}/api/payment/momo/create`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            order_id: order.id,
            amount: total,
            order_number: order.order_number,
          }),
        }
      );
      const payData = await payRes.json();
      if (payData.paymentUrl) {
        return NextResponse.json({
          order_number: order.order_number,
          paymentUrl: payData.paymentUrl,
        });
      }
    }

    // Redeem loyalty points if used
    if (points_used && points_used > 0) {
      try {
        const appUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
        await fetch(`${appUrl}/api/points`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            action: "redeem",
            points: points_used,
            order_id: order.id,
            order_number: order.order_number,
            order_total: subtotal,
          }),
        });
      } catch (err) {
        console.error("[Order] Points redemption failed:", err);
      }
    }

    // Send order confirmation email (non-blocking)
    try {
      const { data: profile } = await supabase
        .from("profiles")
        .select("full_name")
        .eq("id", user.id)
        .single();

      const emailData = buildOrderConfirmationEmail({
        orderNumber: order.order_number,
        customerName: profile?.full_name || "Quý khách",
        items: items.map((item: any) => ({
          name: item.product_name,
          quantity: item.quantity,
          price: item.product_price,
          subtotal: item.subtotal,
        })),
        subtotal,
        deliveryFee: delivery_fee || 0,
        discount: 0,
        total,
        deliveryAddress: delivery_address,
        paymentMethod: payment_method,
        note,
      });

      await sendEmail({ to: user.email!, ...emailData });
    } catch (emailErr) {
      console.error("[Order] Email send failed:", emailErr);
    }

    // COD or Bank Transfer - return success
    return NextResponse.json({
      order_number: order.order_number,
      status: "success",
    });
  } catch (error) {
    console.error("Order API error:", error);
    return NextResponse.json(
      { error: "Lỗi hệ thống" },
      { status: 500 }
    );
  }
}
