-- Add points and gifts tracking to orders
ALTER TABLE orders ADD COLUMN IF NOT EXISTS points_used INT DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS points_discount INT DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS combo_savings INT DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gifts JSONB DEFAULT '[]';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS voucher_code TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS voucher_discount INT DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS points_earned INT DEFAULT 0;
